version: '3.4'

services:
  tor-relay:
    container_name: tor-relay
    hostname: tor-relay
    restart: always
    image: registry.gitlab.com/yoanndelattre/tor-relay-docker:latest
    env_file: .env
    ports:
      - 443:443
    volumes:
      - tor-relay_keys:/var/lib/tor/keys

volumes:
  tor-relay_keys: