version: '3.4'

services:
  tor-relay:
    container_name: tor-relay
    hostname: tor-relay
    restart: always
    image: ghcr.io/yoanndelattre/tor-relay-docker:main
    env_file: .env
    ports:
      - 9001:9001
    volumes:
      - tor-relay_keys:/var/lib/tor/keys
    networks:
      - tor


volumes:
  tor-relay_keys:

networks:
  tor:
