version: '3.4'

services:
  tor-relay:
    container_name: tor-relay
    hostname: tor-relay
    restart: always
    image: registry.gitlab.com/yoanndelattre/tor-relay-docker:latest
    env_file: .env
    ports:
      - 9001:9001
    volumes:
      - tor-relay_keys:/var/lib/tor/keys
    networks:
      - tor
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    depends_on:
      -  tor-relay
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - tor


volumes:
  tor-relay_keys:
  grafana_data:

networks:
  tor: